# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=3)),
                ('detail', models.CharField(max_length=100)),
                ('InputFile', models.ImageField(upload_to='photos')),
                ('submit_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
