# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareHouse', '0003_remove_shareh_inputfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareh',
            name='InputFile',
            field=models.ImageField(default='/static/media/photo/56.jpg', upload_to='photos'),
            preserve_default=False,
        ),
    ]
